### ISSUE TITLE
Missing reference AsterNet.ARI 1.3.1

### ISSUE THREAD

**Issue by shragesmilowitz** [quasarke/arke#12]
[Arke.IVR Here] (https://github.com/quasarke/arke/blob/e4f5f095250644549c4060e9bb8a291debf38561/Arke.IVR/Arke.IVR.csproj#L8) is referencing AsterNet.Ari version 1.3.1 but there is no such version anywhere on nuget or on the AsterNet.Ari repository

**Comment by seiggy** [comment]
Ah, yeah. Thanks. I need to get with the AsterNET.ARI team and get that version published. I'll see if I can get a patch out for that ASAP.

**Comment by seiggy** [comment]
@shrage This should be solved with the latest PR that I just merged. Once AsterNET.ARI 1.3 releases, I'll swap from Arke.ARI back to AsterNET.ARI, but in the mean time, it's available that way.
