### ISSUE TITLE
Null Reference Exceptions At Startup

### ISSUE THREAD

**Issue by shragesmilowitz** [quasarke/arke#14]
_configuration at line 33 is never initialized 

At line 37 there is a call to InitializeConfigurationFileDependencies which in turn calls GetAppSettingsByHostName() which uses _logger which is not initialized yet (Its being initialized at line 38) which causes a null reference exception

At line 38 you try to initialize _logger by using _configuration which is not yet initialized which causes a null reference exception.

**Comment by seiggy** [comment]
@shrage Gotcha, I'll get this patched for you ASAP. We've been using a different host project internally, so I missed this bug as our internal host project has some minor differences.

**Comment by seiggy** [comment]
@shrage So I've verified now that the default setup will connect to ARI (assuming you configure Asterisk correctly) and will answer a call, play a prompt (one of the default prompts included with Asterisk) and then hangup the line. Let me know if you run into any issues. I really need to work on the GUI editor for the Call Flow, as writing the call flow by hand is still a pain in the ass.
