### ISSUE TITLE
 I Want to Change CNAME of Caller 

### ISSUE THREAD

**Issue by MSProgrammer** [quasarke/arke#7]
HI
I want to Change The Caller CNAME With My PhoneBook In Mine Project Database Because i want to Sho my Customize name on SoftPhones And DeskPhone 

Please Help Me , With My knowledge it possible with ARI , I`m Right Or Not?

**Comment by seiggy** [comment]
Not 100%, but no, I don't think you can use ARI to edit endpoints in your Asterisk config. The better thing to do would be to use one of the database integrations and write your own service that allows you to edit the config in the DB. ARI is more for scripting of dialplans in realtime. Not really for config editing.

**Comment by MSProgrammer** [comment]
Hi Seiggy, I solve this problem with ARI 

`sender.Channels.SetChannelVar(e.Channel.Id, "CALLERID(name)", Your String Name);`


just Use `SetChannelvar `with ARI `Stasis`
thank`s Bro
